---
- name: add repository glusterfs server
  hosts: node
  become: yes
  gather_facts: no
  tasks:
    - name: Add glusterfs repository from PPA and install its signing key on Ubuntu target
      ansible.builtin.apt_repository:
        repo: ppa:gluster/glusterfs-9
- name: deploy httpd server
  hosts: node
  become: yes
  gather_facts: no
  tasks:
    - name: install httpd
      apt:
        name: apache2
        state: latest
        update_cache: yes
    - name: start & enabled httpd
      service:
        name: apache2
        state: started
        enabled: yes
- name: deploy glusterfs server
  hosts: node
  become: yes
  gather_facts: no
  tasks:
    - name: gluster install
      apt:
        name: glusterfs-server
        state: latest
        update_cache: yes
    - name: start & enabled glusterfs server
      service:
        name: glusterd
        state: started
        enabled: yes

